[project]
name = "adam-assist"
version = "0.1.0"
description = 'ADAM Core Propagator class using ASSIST'
authors = [
    { name = "Alec Koumjian", email = "akoumjian@gmail.com" },
    { name = "Kathleen Kiker" }
]
readme = "README.md"
keywords = []
requires-python = ">=3.11,<4.0"
dependencies = [
    "adam-core @ git+https://github.com/B612-Asteroid-Institute/adam_core.git@ak/remove-pyoorb",
    "assist",
    "naif-de440",
    "numpy",
    "ray",
    "spiceypy>=6.0.0"
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
[tool.pdm.build]
includes = ["src/adam_core/"]


[project.urls]
"Documentation" = "https://github.com/unknown/adam-assist#readme"
"Issues" = "https://github.com/unknown/adam-assist/issues"
"Source" = "https://github.com/unknown/adam-assist"


[project.optional-dependencies]
dev = [
    "ruff",
    "pdm",
    "mypy",
    "pytest",
    "pytest-cov",
    "pytest-benchmark",
    "black",
    "isort",
    "ipython"
]

[tool.pdm.scripts]
check = {composite = ["lint", "typecheck", "test"]}
format = { composite = ["black ./src/adam_core", "isort ./src/adam_core"]}
lint = { composite = ["ruff check ./src/adam_core", "black --check ./src/adam_core", "isort --check-only ./src/adam_core"] }
fix = "ruff ./src/adam_core --fix"
typecheck = "mypy --strict ./src/adam_core"

test = "pytest --benchmark-disable {args}"
doctest = "pytest --doctest-plus --doctest-only"
benchmark = "pytest --benchmark-only"
coverage = "pytest --cov=src/adam_core/propagators/adam_assist --cov-report=xml"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[tool.mypy]
ignore_missing_imports = true

