name: pip - Build Lint Test and Coverage

on:
  push:
    branches: [ main, "v*"]
  pull_request:
    branches: [ main, "v*"]

jobs:
  build-lint-test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      # Use pip to install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
      # Run linter
      - name: Run linter
        run: |
          pdm run check
      # Run tests
      - name: Run tests
        run: |
          pdm run coverage -v
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: coverage.xml
