name: pip - Build Lint Test and Coverage

on:
  push:
    branches: [ main, "v*"]
  pull_request:
    branches: [ main, "v*"]

jobs:
  build-lint-test-coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
      - name: Get git tags
        run:  git fetch --prune --unshallow --tags
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # # Use pip to install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . --no-cache
          pip install pytest pytest-cov pytest-benchmark --no-cache
      # Run tests
      - name: Run tests
        run: |
          python tests/test_integration.py
      # - name: Coverage report to coveralls
      #   uses: coverallsapp/github-action@v2.0.0
      #   with:
      #     github-token: ${{ secrets.COVERALLS_TOKEN }}
      #     path-to-lcov: coverage.xml
